'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useMemo, useState } from 'react'
import { ArrowLeft, Camera, Check, CircleHelp, Rocket, ShieldCheck, Sparkles, Store } from 'lucide-react'
import BeginnerEconomics from './BeginnerEconomics'

const stages=[['Фото и факты','AI распознаёт только видимое и спрашивает недостающее.'],['Карточка','Заголовок, описание, SEO и план инфографики.'],['Экономика','Цена, комиссия, логистика и минимальная прибыль.'],['Публикация','Превью и отправка в WB/Ozon только после подтверждения.'],['Ведение','Остатки, реклама, отзывы и ежедневные задачи AI Director.']]

export default function BeginnerLaunchWorkspace(){
 const [imageUrl,setImageUrl]=useState(''); const [imageData,setImageData]=useState(''); const [analysis,setAnalysis]=useState(null); const [analysisSignature,setAnalysisSignature]=useState(''); const [productName,setProductName]=useState(''); const [category,setCategory]=useState(''); const [answers,setAnswers]=useState({}); const [factsConfirmed,setFactsConfirmed]=useState(false); const [draft,setDraft]=useState(null); const [factHash,setFactHash]=useState(''); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('')
 const questions=useMemo(()=>analysis?.required_questions||[],[analysis])
 const canGenerate=Boolean(analysis&&analysisSignature&&factsConfirmed&&productName.trim()&&category.trim()&&questions.every((_,i)=>answers[i]?.trim()))
 function resetResult(){setAnalysis(null);setAnalysisSignature('');setAnswers({});setFactsConfirmed(false);setDraft(null);setFactHash('')}
 function choose(file){resetResult();setNotice('');if(!file)return;if(file.size>8*1024*1024){setNotice('Фотография должна быть не больше 8 МБ.');return}const reader=new FileReader();reader.onload=()=>{setImageData(String(reader.result));setImageUrl(String(reader.result))};reader.readAsDataURL(file)}
 async function analyze(){if(!imageData)return;setBusy(true);setNotice('AI изучает фото и отделяет видимые факты от того, что нужно уточнить…');try{const r=await fetch('/api/beginner/analyze-photo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image_data_url:imageData})});const p=await r.json();if(!r.ok)throw new Error(p.error||'Не удалось проанализировать фото');setAnalysis(p.analysis);setAnalysisSignature(p.analysis_signature);setProductName(p.analysis.product_name_guess||'');setCategory(p.analysis.category_guess||'');setNotice('Первый шаг готов. Проверьте предположения, подтвердите видимые факты и ответьте на вопросы.')}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 async function generate(){if(!canGenerate)return;setBusy(true);setNotice('Собираем защищённый набор фактов и создаём черновик для WB и Ozon…');const confirmed=[{label:'Название товара',value:productName.trim()},{label:'Категория',value:category.trim()},...(analysis.visible_facts||[]).map(x=>({label:x.label,value:x.value})),...questions.map((question,i)=>({label:question,value:answers[i].trim()}))];try{const r=await fetch('/api/beginner/generate-draft',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({analysis,analysis_signature:analysisSignature,confirmed_facts:confirmed})});const p=await r.json();if(!r.ok)throw new Error(p.error||'Не удалось создать карточку');setDraft(p.draft);setFactHash(p.fact_set_sha256);setNotice('Черновик готов по подтверждённым фактам. Он ещё не опубликован — сначала проверка и расчёт экономики.')}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 return <main className="launchPage"><header className="launchTop"><Link href="/" className="ghostBtn"><ArrowLeft size={16}/> В панель</Link><div><span>Старт с нуля</span><b>для нового продавца</b></div><Link href="/account" className="ghostBtn"><Store size={16}/> Подключить магазин</Link></header>
 <section className="launchIntro"><div><span className="launchBadge"><Rocket size={15}/> Новый товарный проект</span><h1>Начните с одного фото товара</h1><p>Загрузите снимок с телефона. AI определит, что действительно видно, задаст несколько вопросов и соберёт безопасный план запуска на Wildberries и Ozon.</p></div><div className="launchPromise"><ShieldCheck size={24}/><strong>Никаких выдуманных характеристик</strong><span>Материал, размеры, состав и сертификаты подтверждает продавец.</span></div></section>
 <section className="launchFlow"><div className="launchStages">{stages.map(([title,text],i)=><article className={i===(draft?1:0)?'current':''} key={title}><span>{i+1}</span><div><strong>{title}</strong><small>{text}</small></div></article>)}</div>
 <div className="launchWork"><section className="photoDesk"><div className="photoDrop">{imageUrl?<Image src={imageUrl} alt="Загруженный товар" fill sizes="(max-width: 900px) 100vw, 42vw" unoptimized/>:<><Camera size={34}/><strong>Добавьте главное фото</strong><span>JPG, PNG или WebP · до 8 МБ</span></>}<input aria-label="Фотография товара" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>choose(e.target.files?.[0])}/></div><button className="launchAction" disabled={!imageData||busy} onClick={analyze}><Sparkles size={18}/>{busy&&!analysis?' Анализируем…':' Разобрать фото через AI'}</button><small className="privacyLine">Фото отправляется только в серверный AI-анализ и не публикуется в маркетплейсе.</small></section>
 <section className="analysisDesk">{analysis?<><div className="analysisTitle"><div><span>Проверьте предположение AI</span><h2>{analysis.product_name_guess||'Товар'}</h2><p>{analysis.category_guess||'Категория требует уточнения'} · уверенность: {analysis.confidence}</p></div><Check size={22}/></div><div className="confirmGrid"><label><span>Название товара</span><input value={productName} onChange={e=>{setProductName(e.target.value);setDraft(null)}}/></label><label><span>Категория</span><input value={category} onChange={e=>{setCategory(e.target.value);setDraft(null)}}/></label></div><h3>Что видно на фото</h3><div className="visibleFacts">{analysis.visible_facts.length?analysis.visible_facts.map((x,i)=><div key={`${x.label}-${i}`}><span>{x.label}</span><strong>{x.value}</strong></div>):<p>Надёжные характеристики по этому фото не определены.</p>}</div><h3>Ответьте на обязательные вопросы</h3><div className="questionInputs">{questions.map((x,i)=><label key={`${i}-${x}`}><span><CircleHelp size={16}/>{x}</span><input value={answers[i]||''} placeholder="Ответ продавца" onChange={e=>{setAnswers(v=>({...v,[i]:e.target.value}));setDraft(null)}}/></label>)}</div><label className="factConsent"><input type="checkbox" checked={factsConfirmed} onChange={e=>{setFactsConfirmed(e.target.checked);setDraft(null)}}/><span>Я проверил(а) название, категорию и видимые признаки. Эти данные можно использовать как факты карточки.</span></label><button className="launchAction" disabled={!canGenerate||busy} onClick={generate}><Sparkles size={18}/>{busy?' Создаём карточку…':' Создать карточку WB/Ozon'}</button>{analysis.photo_warnings.length>0&&<div className="photoTips"><strong>Для лучшей карточки</strong>{analysis.photo_warnings.map((x,i)=><span key={`${i}-${x}`}>{x}</span>)}</div>}</>:<div className="analysisEmpty"><Sparkles size={30}/><h2>Здесь появится разбор</h2><p>AI не будет угадывать скрытые свойства. Он покажет видимые признаки и список коротких вопросов.</p></div>}</section></div>
 {draft&&<><section className="beginnerDraft"><div className="draftHeader"><div><span>Безопасный AI-черновик</span><h2>Карточка готова к проверке</h2></div><b>Не опубликовано</b></div><div className="marketTitles"><article><span>Wildberries</span><h3>{draft.wb_title}</h3></article><article><span>Ozon</span><h3>{draft.ozon_title}</h3></article></div><div className="draftBody"><article><h3>Описание</h3><p>{draft.description}</p><h3>SEO-фразы</h3><div className="draftChips">{draft.seo_phrases.map(x=><span key={x}>{x}</span>)}</div></article><article><h3>План изображений</h3><ol>{draft.visual_plan.map((x,i)=><li key={`${i}-${x}`}>{x}</li>)}</ol></article></div><footer><span>Набор фактов: {factHash.slice(0,12)}…</span><button onClick={()=>document.getElementById('beginner-economics')?.scrollIntoView({behavior:'smooth'})}>Перейти к экономике</button></footer></section><BeginnerEconomics/></>}
 </section>
 {notice&&<div className="launchNotice">{notice}</div>}
 <section className="launchNext"><div><h2>После подтверждения фактов</h2><p>Система подготовит карточку, рассчитает экономику, покажет превью публикации и затем возьмёт магазин под ежедневное наблюдение.</p></div><div><span><Check size={16}/> Заголовок и SEO</span><span><Check size={16}/> Описание и характеристики</span><span><Check size={16}/> План инфографики</span><span><Check size={16}/> Контроль прибыли</span><span><Check size={16}/> Остатки и реклама</span><span><Check size={16}/> Ответы на отзывы</span></div></section>
 </main>
}
