'use client'

import { useMemo, useState } from 'react'
import { Calculator, ShieldAlert, ShieldCheck } from 'lucide-react'

const initial={marketplace:'wildberries',price:'',cogs:'',commission_percent:'',logistics:'',ads_per_order:'0',tax_percent:'',returns_reserve:'0',other_costs:'0',target_margin_percent:'15'}
const money=value=>new Intl.NumberFormat('ru-RU',{minimumFractionDigits:0,maximumFractionDigits:2}).format(value||0)+' ₽'

export default function BeginnerEconomics(){
 const [form,setForm]=useState(initial); const [confirmed,setConfirmed]=useState(false); const [result,setResult]=useState(null); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('')
 const required=['price','cogs','commission_percent','logistics','tax_percent']
 const ready=useMemo(()=>confirmed&&required.every(key=>form[key]!==''&&Number(form[key])>=0)&&Number(form.price)>0,[form,confirmed])
 const fields=[['price','Цена продажи','₽'],['cogs','Себестоимость товара','₽'],['commission_percent','Комиссия площадки','%'],['logistics','Логистика на единицу','₽'],['ads_per_order','Реклама на заказ','₽'],['tax_percent','Налог','%'],['returns_reserve','Резерв на возвраты','₽'],['other_costs','Другие расходы','₽'],['target_margin_percent','Целевая маржа','%']]
 function change(key,value){setForm(current=>({...current,[key]:value}));setResult(null)}
 async function calculate(){if(!ready)return;setBusy(true);setNotice('Считаем без AI — только по введённым цифрам.');try{const response=await fetch('/api/beginner/calculate-economics',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,rates_confirmed_by_seller:confirmed})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Не удалось выполнить расчёт');setResult(payload);setNotice(payload.safe_to_launch?'Экономика проходит заданную защиту по марже. Публикация всё равно потребует подтверждения.':'Запуск заблокирован: исправьте цену или расходы.') }catch(error){setNotice(error.message)}finally{setBusy(false)}}
 return <section id="beginner-economics" className="economicsDesk"><div className="economicsHead"><div><span>Шаг 3 · экономика</span><h2>Не запустить товар в убыток</h2><p>Сначала вводим реальные расходы. AI не участвует в арифметике и не придумывает тарифы WB/Ozon.</p></div><Calculator size={28}/></div><div className="economicsGrid"><div className="economicsForm"><label>Маркетплейс<select value={form.marketplace} onChange={event=>change('marketplace',event.target.value)}><option value="wildberries">Wildberries</option><option value="ozon">Ozon</option></select></label>{fields.map(([key,label,suffix])=><label key={key}><span>{label}</span><div><input type="number" min="0" step="0.01" value={form[key]} placeholder={required.includes(key)?'Обязательно':'0'} onChange={event=>change(key,event.target.value)}/><b>{suffix}</b></div></label>)}<label className="rateConsent"><input type="checkbox" checked={confirmed} onChange={event=>{setConfirmed(event.target.checked);setResult(null)}}/><span>Я проверил(а) комиссию и логистику в кабинете маркетплейса. Это мои подтверждённые значения.</span></label><button className="economicsAction" disabled={!ready||busy} onClick={calculate}>{busy?'Считаем…':'Проверить экономику'}</button></div><div className="economicsResult">{result?<><div className={result.safe_to_launch?'launchVerdict safe':'launchVerdict blocked'}>{result.safe_to_launch?<ShieldCheck size={25}/>:<ShieldAlert size={25}/>}<div><span>{result.safe_to_launch?'Можно переходить к проверке':'Публикация заблокирована'}</span><strong>{money(result.profit_per_unit)} с единицы</strong></div></div><div className="economicsMetrics"><div><span>Маржа</span><strong>{result.margin_percent}%</strong></div><div><span>Все расходы</span><strong>{money(result.costs.total)}</strong></div><div><span>Безубыточность</span><strong>{result.break_even_price===null?'невозможно':money(result.break_even_price)}</strong></div><div><span>Минимальная цена для цели</span><strong>{result.recommended_min_price===null?'невозможно':money(result.recommended_min_price)}</strong></div></div>{result.blockers.length>0&&<div className="economicsBlockers"><strong>Что нужно исправить</strong>{result.blockers.map(item=><span key={item}>{item}</span>)}</div>}<small>Источник тарифов: подтверждены продавцом · публикация не выполнялась</small></>:<div className="economicsEmpty"><Calculator size={30}/><strong>Введите реальные цифры</strong><span>Результат покажет прибыль с единицы, точку безубыточности и безопасную минимальную цену.</span></div>}</div></div>{notice&&<div className="economicsNotice">{notice}</div>}</section>
}
