'use client'

import Link from 'next/link'
import Image from 'next/image'
import { useSearchParams } from 'next/navigation'
import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ArrowLeft, Building2, CheckCircle2, Clock3, LockKeyhole, RefreshCcw, Send, Sparkles } from 'lucide-react'
import { useActiveStore } from '../lib/useActiveStore'

function savedDraft(item){return item?.result?{...item.result,generation_id:item.id,created_at:item.created_at}:null}

export default function CardFactoryWorkspace(){
 const params=useSearchParams(); const nmId=Number(params.get('nm_id')||0)
 const {storeId,storeName,loading:storeLoading,error:storeError}=useActiveStore()
 const [source,setSource]=useState(null); const [generated,setGenerated]=useState(null); const [history,setHistory]=useState([]); const [assets,setAssets]=useState([]); const [publications,setPublications]=useState([]); const [mediaPublications,setMediaPublications]=useState([])
 const [tab,setTab]=useState('WB'); const [notice,setNotice]=useState(''); const [busy,setBusy]=useState(false); const [imageBusy,setImageBusy]=useState(-1)
 const [review,setReview]=useState(null); const [approved,setApproved]=useState(false); const [confirmation,setConfirmation]=useState(''); const [publishBusy,setPublishBusy]=useState(false)
 const [mediaReview,setMediaReview]=useState(null); const [mediaApproved,setMediaApproved]=useState(false); const [mediaConfirmation,setMediaConfirmation]=useState(''); const [mediaBusy,setMediaBusy]=useState(false)

 useEffect(()=>{if(!storeId||!nmId){setSource(null);return}let alive=true;setBusy(true);setNotice('Загружаем подтверждённые факты из каталога WB…');fetch(`/api/card-factory/card/${nmId}?store_id=${encodeURIComponent(storeId)}`,{cache:'no-store'}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error||'Не удалось загрузить карточку');if(!alive)return;setSource(p);setGenerated(null);setReview(null);setMediaReview(null);setNotice('Карточка загружена. Набор фактов зафиксирован на сервере и недоступен для подмены.')}).catch(e=>alive&&setNotice(e.message)).finally(()=>alive&&setBusy(false));return()=>{alive=false}},[storeId,nmId])
 useEffect(()=>{if(!storeId||!nmId)return;let alive=true;Promise.all([
  fetch(`/api/card-factory/generations?store_id=${encodeURIComponent(storeId)}&nm_id=${nmId}`,{cache:'no-store'}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error||'Не удалось загрузить историю AI');return p}),
  fetch(`/api/card-factory/publications?store_id=${encodeURIComponent(storeId)}&nm_id=${nmId}`,{cache:'no-store'}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error||'Не удалось загрузить историю публикаций');return p}),
  fetch(`/api/card-factory/media-publications?store_id=${encodeURIComponent(storeId)}&nm_id=${nmId}`,{cache:'no-store'}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error||'Не удалось загрузить историю изображений');return p}),
 ]).then(([generationData,publicationData,mediaData])=>{if(!alive)return;const items=generationData.items||[];const publicationItems=publicationData.items||[];const mediaItems=mediaData.items||[];setHistory(items);setAssets(items.filter(x=>x.feature==='card_factory_visual'&&x.status==='completed'&&x.result?.storage_status==='stored'));const latest=items.find(x=>x.feature==='card_factory_copy'&&x.status==='completed'&&x.result);if(latest)setGenerated(savedDraft(latest));setPublications(publicationItems);setMediaPublications(mediaItems);const latestSubmitted=publicationItems.find(x=>x.status==='submitted');if(latestSubmitted)setReview(latestSubmitted);const latestMedia=mediaItems.find(x=>x.status==='submitted');if(latestMedia)setMediaReview(latestMedia)}).catch(e=>alive&&setNotice(e.message));return()=>{alive=false}},[storeId,nmId])

 const facts=source?.fact_set?.facts||[]
 const copyVersions=history.filter(x=>x.feature==='card_factory_copy'&&x.status==='completed'&&x.result)
 const ready=useMemo(()=>Boolean(storeId&&nmId&&facts.length&&!busy),[storeId,nmId,facts.length,busy])
 const canPublish=Boolean(review&&review.status!=='submitted'&&approved&&confirmation.trim().toUpperCase()==='ОПУБЛИКОВАТЬ'&&!publishBusy)
 const canPublishMedia=Boolean(mediaReview&&mediaReview.status!=='submitted'&&mediaApproved&&mediaConfirmation.trim().toUpperCase()==='ОПУБЛИКОВАТЬ ФОТО'&&!mediaBusy)

 function chooseVersion(item){setGenerated(savedDraft(item));setReview(null);setApproved(false);setConfirmation('');setNotice(`Выбрана сохранённая версия ${item.id.slice(0,8)}. Перед публикацией сервер заново проверит её факты.`)}
 async function generate(){setBusy(true);setReview(null);setApproved(false);setConfirmation('');setNotice('AI улучшает карточку и проверяет результат по исходным фактам…');try{const r=await fetch('/api/card-factory/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({store_id:storeId,nm_id:nmId})});const p=await r.json();if(!r.ok)throw new Error(p.error||'Не удалось создать AI-черновик');const item={id:p.generation_id,feature:'card_factory_copy',status:'completed',result:p.draft,created_at:new Date().toISOString()};setGenerated(savedDraft(item));setHistory(items=>[item,...items]);setNotice('AI-черновик сохранён как отдельная версия. Публикация в WB не выполнялась.')}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 async function generateVisual(visualIndex){setImageBusy(visualIndex);setNotice('AI создаёт визуал по реальному фото товара и сохраняет его в постоянное хранилище…');try{const r=await fetch('/api/card-factory/generate-visual',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({store_id:storeId,nm_id:nmId,visual_index:visualIndex})});const p=await r.json();if(!r.ok)throw new Error(p.error||'Не удалось создать визуал');setAssets(items=>[p.generation,...items]);setHistory(items=>[p.generation,...items]);setNotice('Визуал сохранён как отдельная версия. Он не опубликован.')}catch(e){setNotice(e.message)}finally{setImageBusy(-1)}}
 async function prepareReview(){if(!generated?.generation_id)return;setPublishBusy(true);setNotice('Сервер сверяет выбранную версию с текущим снимком карточки…');try{const r=await fetch('/api/card-factory/publications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({store_id:storeId,nm_id:nmId,generation_id:generated.generation_id})});const p=await r.json();if(!r.ok)throw new Error(p.error||'Не удалось подготовить сравнение');setReview(p);setApproved(false);setConfirmation('');setPublications(items=>[p,...items.filter(x=>x.id!==p.id)]);setNotice('Сравнение зафиксировано. Проверьте оба поля и подтвердите именно эту версию.')}catch(e){setNotice(e.message)}finally{setPublishBusy(false)}}
 async function publish(){if(!canPublish)return;setPublishBusy(true);setNotice('Получаем свежую карточку из WB и проверяем, что она не менялась…');try{const r=await fetch(`/api/card-factory/publications/${review.id}/publish`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({store_id:storeId,payload_sha256:review.payload_sha256,confirmation})});const p=await r.json();if(!r.ok)throw new Error(p.error||'WB не принял обновление');setReview(p);setPublications(items=>[p,...items.filter(x=>x.id!==p.id)]);setNotice('Версия отправлена в Wildberries на обработку. Мы сохранили подтверждение и ответ API; автоматическая повторная отправка отключена.')}catch(e){setNotice(e.message)}finally{setPublishBusy(false)}}
 async function verifyPublication(){if(!review?.id||review.status!=='submitted')return;setPublishBusy(true);setNotice('Повторно читаем карточку напрямую из WB и сравниваем с отправленной версией…');try{const r=await fetch(`/api/card-factory/publications/${review.id}/verify`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({store_id:storeId})});const p=await r.json();if(!r.ok)throw new Error(p.error||'Не удалось проверить публикацию');setReview(p);setPublications(items=>[p,...items.filter(x=>x.id!==p.id)]);setNotice(p.verification_status==='applied'?'WB уже возвращает именно отправленный заголовок и описание. Публикация подтверждена.':p.verification_status==='pending'?'WB пока возвращает прежнюю версию. Изменение ещё обрабатывается — повторная отправка не нужна.':'WB возвращает другие значения. Автоматических повторных изменений не выполняем; проверьте карточку и подготовьте новую версию.')}catch(e){setNotice(e.message)}finally{setPublishBusy(false)}}
 async function prepareMedia(asset){setMediaBusy(true);setNotice('Фиксируем выбранный визуал и следующую свободную позицию в карточке WB…');try{const r=await fetch('/api/card-factory/media-publications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({store_id:storeId,nm_id:nmId,generation_id:asset.id})});const p=await r.json();if(!r.ok)throw new Error(p.error||'Не удалось подготовить изображение');setMediaReview(p);setMediaApproved(false);setMediaConfirmation('');setMediaPublications(items=>[p,...items.filter(x=>x.id!==p.id)]);setNotice('Изображение подготовлено отдельно от текста. Проверьте версию и явно подтвердите загрузку.')}catch(e){setNotice(e.message)}finally{setMediaBusy(false)}}
 async function publishMedia(){if(!canPublishMedia)return;setMediaBusy(true);setNotice('Проверяем текущие фото, размер файла и права WB перед загрузкой…');try{const r=await fetch(`/api/card-factory/media-publications/${mediaReview.id}/publish`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({store_id:storeId,payload_sha256:mediaReview.payload_sha256,confirmation:mediaConfirmation})});const p=await r.json();if(!r.ok)throw new Error(p.error||'WB не принял изображение');setMediaReview(p);setMediaPublications(items=>[p,...items.filter(x=>x.id!==p.id)]);setNotice('Изображение отправлено в следующую свободную позицию WB. Существующие фото не заменялись; автоматический повтор отключён.')}catch(e){setNotice(e.message)}finally{setMediaBusy(false)}}
 async function verifyMedia(){if(!mediaReview?.id||mediaReview.status!=='submitted')return;setMediaBusy(true);setNotice('Проверяем количество и порядок фотографий прямо в WB…');try{const r=await fetch(`/api/card-factory/media-publications/${mediaReview.id}/verify`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({store_id:storeId})});const p=await r.json();if(!r.ok)throw new Error(p.error||'Не удалось проверить изображение');setMediaReview(p);setMediaPublications(items=>[p,...items.filter(x=>x.id!==p.id)]);setNotice(p.verification_status==='applied'?'Новое изображение появилось, а прежние фото сохранили порядок.':p.verification_status==='pending'?'WB ещё обрабатывает изображение. Повторно отправлять его не нужно.':'Набор фотографий отличается от подготовленного. TROVENDI остановил дальнейшие изменения.')}catch(e){setNotice(e.message)}finally{setMediaBusy(false)}}

 const title=tab==='WB'?generated?.wb_title:generated?.ozon_title
 return <main className="workPage"><div className="workHead"><Link href="/products" className="ghostBtn"><ArrowLeft size={16}/> К товарам</Link><Link href="/account" className="ghostBtn">Подключения</Link></div>
 <section className="workHero"><span className="eyebrow">AI КОНТЕНТ · РЕАЛЬНАЯ КАРТОЧКА</span><h1>AI Card Factory</h1><p>Backend загружает карточку по nmId из выбранного магазина, фиксирует подтверждённые WB-факты и только после этого запускает AI.</p><div className="sectionStoreContext"><Building2 size={16}/><span>{storeLoading?'Загружаем магазин…':storeId?`Активный магазин: ${storeName}`:'Активный магазин не выбран'}</span></div></section>
 {storeError&&<div className="sectionNotice">{storeError}</div>}{!nmId&&<div className="sectionNotice">Откройте товар в разделе «Товары» и нажмите «Улучшить через AI» — Card Factory нужен реальный nmId.</div>}
 <div className="factoryGrid"><section className="workPanel formPanel"><h2>Подтверждённые данные</h2>{source?<><div className="lockedCard"><div><span className="eyebrow">WB КАРТОЧКА</span><h3>{source.card.title||`Товар ${nmId}`}</h3><small>{source.card.vendor_code} · nmId {nmId}</small></div><LockKeyhole size={20}/></div><div className="factList">{facts.map(x=><div key={x.id}><span>{x.label}</span><strong>{x.value}</strong></div>)}</div><small className="factHash">Fact set: {source.fact_set.sha256.slice(0,16)}… · {facts.length} фактов</small></>:<div className="emptyFacts">{busy?'Загружаем карточку…':'Карточка не выбрана или ещё не синхронизирована.'}</div>}<button className="primaryBtn" disabled={!ready} onClick={generate}><Sparkles size={17}/>{busy?' Проверяем…':' Сгенерировать через AI'}</button>
 {copyVersions.length>0&&<div className="versionList"><span className="eyebrow">СОХРАНЁННЫЕ ВЕРСИИ</span>{copyVersions.map((item,index)=><button key={item.id} className={generated?.generation_id===item.id?'selected':''} onClick={()=>chooseVersion(item)}><span>Версия {copyVersions.length-index}</span><small>{item.id.slice(0,8)} · {item.created_at?new Date(item.created_at).toLocaleString('ru-RU'):'сохранена'}</small></button>)}</div>}
 </section>
 <section className="workPanel previewPanel"><div className="previewTabs"><button className={tab==='WB'?'active':''} onClick={()=>setTab('WB')}>Wildberries</button><button className={tab==='Ozon'?'active':''} onClick={()=>setTab('Ozon')}>Ozon</button></div>{generated?<div className="previewContent"><span className="eyebrow">ЗАГОЛОВОК</span><h2>{title}</h2><span className="eyebrow">ОПИСАНИЕ</span><p>{generated.description}</p><span className="eyebrow">SEO ФРАЗЫ</span><div className="chips">{(generated.seo_phrases||[]).map(x=><span key={x}>{x}</span>)}</div>{assets.length>0&&<><span className="eyebrow">СОХРАНЁННЫЕ ВИЗУАЛЫ</span><div className="assetGrid">{assets.map(asset=><div key={asset.id}><Image src={asset.result.url} alt="AI-визуал карточки" width={420} height={420} unoptimized/><small>Версия {asset.id.slice(0,8)}</small>{tab==='WB'&&<button disabled={mediaBusy} onClick={()=>prepareMedia(asset)}>Подготовить фото для WB</button>}</div>)}</div></>}<span className="eyebrow">ВИЗУАЛЬНЫЙ ПЛАН</span><div className="visualPlan">{(generated.visual_plan||[]).map((x,i)=><div className="visualPlanRow" key={`${i}-${x}`}><span>{i+1}. {x}</span><button disabled={imageBusy>=0} onClick={()=>generateVisual(i)}>{imageBusy===i?'Создаём…':'Создать визуал'}</button></div>)}</div>{tab==='WB'?<button className="primaryBtn" disabled={publishBusy} onClick={prepareReview}><CheckCircle2 size={17}/>{publishBusy?' Проверяем…':' Сравнить текст перед публикацией'}</button>:<div className="publishHint">Публикацию Ozon подключим после безопасного полного цикла WB.</div>}</div>:<div className="emptyPreview">Здесь появится AI-черновик после серверной проверки по фактам карточки.</div>}</section></div>
 {review&&<section className="workPanel publicationReview"><div className="reviewHeading"><div><span className="eyebrow">ПРОВЕРКА ВЕРСИИ {review.generation_id.slice(0,8)}</span><h2>{review.status==='submitted'?'Отправлено в Wildberries':'До и после'}</h2></div>{review.status==='submitted'&&<CheckCircle2 className="submittedIcon" size={28}/>}</div><div className="diffGrid">{['title','description'].map(field=><article key={field}><h3>{field==='title'?'Заголовок':'Описание'}</h3><div><span>Сейчас в WB</span><p>{review.diff[field].before||'Не заполнено'}</p></div><div className="after"><span>Будет отправлено</span><p>{review.diff[field].after}</p></div></article>)}</div><div className="unchangedFields"><LockKeyhole size={16}/> Без изменений: бренд, габариты, характеристики, размеры и баркоды.</div>{review.status!=='submitted'&&<div className="confirmationBox"><label className="approvalCheck"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/><span>Я проверил заголовок и описание и подтверждаю отправку именно этой версии.</span></label><label><span>Введите ОПУБЛИКОВАТЬ</span><input value={confirmation} onChange={e=>setConfirmation(e.target.value)} placeholder="ОПУБЛИКОВАТЬ" autoComplete="off"/></label><button className="dangerPublishBtn" disabled={!canPublish} onClick={publish}><Send size={17}/>{publishBusy?' Проверяем WB…':' Отправить в Wildberries'}</button><small>Перед отправкой сервер ещё раз получает карточку из WB. Если кто-то изменил её после подготовки, публикация блокируется.</small></div>}</section>}
 {review?.status==='submitted'&&<section className={`workPanel verificationBox ${review.verification_status||'not_checked'}`}><div className="verificationIcon">{review.verification_status==='applied'?<CheckCircle2/>:review.verification_status==='mismatch'?<AlertTriangle/>:<Clock3/>}</div><div><strong>{review.verification_status==='applied'?'Применение подтверждено':review.verification_status==='mismatch'?'Обнаружено расхождение':review.verification_status==='pending'?'WB ещё показывает прежнюю версию':'Нужно проверить применение'}</strong><span>{review.last_verified_at?`Последняя проверка: ${new Date(review.last_verified_at).toLocaleString('ru-RU')}`:'После отправки TROVENDI повторно прочитает карточку из WB.'}</span></div><button onClick={verifyPublication} disabled={publishBusy}><RefreshCcw size={16}/>{publishBusy?' Проверяем…':' Проверить в WB'}</button></section>}
 {mediaReview&&<section className="workPanel mediaReview"><div className="reviewHeading"><div><span className="eyebrow">ОТДЕЛЬНАЯ ПУБЛИКАЦИЯ ИЗОБРАЖЕНИЯ</span><h2>{mediaReview.status==='submitted'?'Изображение отправлено в WB':`Новое фото в позицию ${mediaReview.diff.target_position}`}</h2></div><Image src={mediaReview.asset.url} alt="Выбранный AI-визуал" width={112} height={112} unoptimized/></div><div className="mediaDiff"><span>Сейчас: {mediaReview.diff.before_photo_count} фото</span><strong>После обработки: {mediaReview.diff.after_photo_count} фото</strong><small>Все существующие изображения и их порядок сохраняются.</small></div>{mediaReview.status!=='submitted'?<div className="confirmationBox"><label className="approvalCheck"><input type="checkbox" checked={mediaApproved} onChange={e=>setMediaApproved(e.target.checked)}/><span>Я проверил выбранное изображение и подтверждаю его добавление в карточку.</span></label><label><span>Введите ОПУБЛИКОВАТЬ ФОТО</span><input value={mediaConfirmation} onChange={e=>setMediaConfirmation(e.target.value)} placeholder="ОПУБЛИКОВАТЬ ФОТО" autoComplete="off"/></label><button className="dangerPublishBtn" disabled={!canPublishMedia} onClick={publishMedia}><Send size={17}/>{mediaBusy?' Проверяем WB…':' Добавить фото в Wildberries'}</button><small>Перед загрузкой TROVENDI заново проверяет карточку и требования WB: формат, размер и разрешение.</small></div>:<div className={`verificationBox ${mediaReview.verification_status||'pending'}`}><div className="verificationIcon">{mediaReview.verification_status==='applied'?<CheckCircle2/>:mediaReview.verification_status==='mismatch'?<AlertTriangle/>:<Clock3/>}</div><div><strong>{mediaReview.verification_status==='applied'?'Фото подтверждено в WB':mediaReview.verification_status==='mismatch'?'Набор фото изменился':'WB обрабатывает изображение'}</strong><span>{mediaReview.last_verified_at?`Последняя проверка: ${new Date(mediaReview.last_verified_at).toLocaleString('ru-RU')}`:'Повторная загрузка автоматически не выполняется.'}</span></div><button onClick={verifyMedia} disabled={mediaBusy}><RefreshCcw size={16}/>{mediaBusy?' Проверяем…':' Проверить фото в WB'}</button></div>}</section>}
 {publications.length>0&&<div className="sectionNotice">Текстовых отправок: {publications.length}. Последний статус: {publications[0].status} · проверка: {publications[0].verification_status||'не запускалась'}.</div>}{mediaPublications.length>0&&<div className="sectionNotice">Отправок изображений: {mediaPublications.length}. Последний статус: {mediaPublications[0].status} · проверка: {mediaPublications[0].verification_status||'не запускалась'}.</div>}{generated?.generation_id&&<div className="sectionNotice">Версия AI: {generated.generation_id} · текстовых версий: {copyVersions.length} · визуалов: {assets.length}. История хранится на сервере.</div>}{notice&&<div className="sectionNotice">{notice}</div>}</main>
}
