'use client'

import Link from 'next/link'
import { useCallback,useEffect,useState } from 'react'
import { ArrowLeft,Boxes,Check,ChevronRight,Clock3,Database,Factory,RefreshCw,ShieldCheck,ShoppingBag,Tags } from 'lucide-react'
import { useActiveStore } from '../lib/useActiveStore'

const models=[
 {key:'reseller',icon:ShoppingBag,title:'Реселлер / импортёр',text:'Закупаю готовые товары и перепродаю.',answers:{buys_finished_goods:true,makes_products:false,controls_rrp:false}},
 {key:'manufacturer',icon:Factory,title:'Собственное производство',text:'Произвожу или собираю товары сам.',answers:{buys_finished_goods:false,makes_products:true,controls_rrp:false}},
 {key:'distributor',icon:Tags,title:'Официальный дистрибьютор',text:'Представляю бренды и контролирую РРЦ.',answers:{buys_finished_goods:true,makes_products:false,controls_rrp:true}},
 {key:'mixed',icon:Boxes,title:'Смешанная модель',text:'Совмещаю производство, закупки или дистрибуцию.',answers:{buys_finished_goods:true,makes_products:true,controls_rrp:false}},
]

export default function OnboardingWorkspace(){
 const {storeId,storeName,loading:storeLoading,error:storeError}=useActiveStore();const [data,setData]=useState(null);const [selected,setSelected]=useState('');const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false);const [importing,setImporting]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('')
 const load=useCallback(async()=>{if(!storeId){setData(null);return}setLoading(true);setError('');try{const response=await fetch(`/api/onboarding?store_id=${encodeURIComponent(storeId)}`,{cache:'no-store'});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Не удалось проверить магазин');setData(payload);setSelected(payload.profile?.operating_model||'')}catch(e){setError(e.message)}finally{setLoading(false)}},[storeId])
 useEffect(()=>{load()},[load])
 const importState=data?.import?.groups?.map(item=>item.state).join('|')||''
 useEffect(()=>{if(!storeId||data?.import?.complete||!/(syncing|retrying)/.test(importState))return;const timer=setInterval(load,5000);return()=>clearInterval(timer)},[storeId,data?.import?.complete,importState,load])
 async function confirm(){const option=models.find(item=>item.key===selected);if(!option||!storeId)return;setSaving(true);setError('');setNotice('');try{const response=await fetch('/api/onboarding',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({store_id:storeId,operating_model:option.key,...option.answers})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Не удалось подтвердить профиль');setData(payload);setNotice('Профиль подтверждён. Финансовые параметры по-прежнему потребуют отдельных проверенных данных продавца.')}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function startImport(){if(!storeId)return;setImporting(true);setError('');setNotice('');try{const response=await fetch('/api/onboarding',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({store_id:storeId})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Не удалось запустить импорт');setNotice(payload.message);await load()}catch(e){setError(e.message)}finally{setImporting(false)}}
 const evidence=data?.evidence||{}
 return <main className="onboardingPage"><header className="onboardingTop"><Link href="/" className="ghostBtn"><ArrowLeft size={16}/> В панель</Link><span>AI-Мастер настройки</span><Link href="/start" className="ghostBtn">Новый товар</Link></header><section className="onboardingBody">
  <div className="onboardingHero"><div><span className="eyebrow">TROVENDI · ПЕРВЫЙ ЗАПУСК</span><h1>{storeName?`Настраиваем «${storeName}»`:'Настройте первый магазин'}</h1><p>Мастер проверяет подключение, импортирует факты и показывает три первых действия без выдуманных показателей.</p></div><div className="setupScore"><strong>{data?.completion_percent??0}%</strong><span>{data?.status==='ready'?'готово к работе':'настройки завершено'}</span></div></div>
  {(error||storeError)&&<div className="setupNotice error">{error||storeError}</div>}{notice&&<div className="setupNotice">{notice}</div>}
  <section className="setupSteps">{data?.steps?.map((step,index)=><article className={step.complete?'complete':''} key={step.key}><span>{step.complete?<Check size={16}/>:index+1}</span><b>{step.label}</b></article>)||<p>{storeLoading||loading?'Проверяем магазин…':'Выберите магазин в аккаунте.'}</p>}<button onClick={load} disabled={loading||!storeId}><RefreshCw size={15}/>{loading?' Проверяем…':' Проверить снова'}</button></section>
  <section className="importPanel"><div className="importHeader"><div><span>Первый импорт</span><h2>Данные продолжают загружаться в фоне</h2><p>{data?.import?.message||'После подключения WB запустите защищённый read-only импорт.'}</p></div><strong>{data?.import?.progress_percent??0}%</strong></div><div className="progressTrack"><i style={{width:`${data?.import?.progress_percent??0}%`}}/></div><div className="importGroups">{data?.import?.groups?.map(item=><article className={item.state} key={item.key}>{item.state==='complete'?<Check size={17}/>:item.state==='syncing'||item.state==='retrying'?<RefreshCw size={17}/>:item.state==='error'?<Database size={17}/>:<Clock3 size={17}/>}<div><b>{item.label}</b><span>{item.state==='complete'?'Готово':item.state==='syncing'?'Загружается':item.state==='retrying'?`Повтор ${item.job?.attempts||0} из ${item.job?.max_attempts||5}`:item.state==='error'?'Нужен безопасный повтор':'Ожидает запуска'}</span></div></article>)}</div><button className="startImport" onClick={startImport} disabled={importing||!storeId||data?.import?.complete}>{importing?'Ставим задачи в очередь…':data?.import?.progress_percent?'Продолжить или восстановить импорт':'Запустить полный импорт WB'}</button></section>
  <section className="evidencePanel"><div><span>Факты после сканирования</span><h2>Что TROVENDI уже знает</h2></div><div className="evidenceGrid"><article><strong>{evidence.catalog_cards??'—'}</strong><span>карточек WB</span></article><article><strong>{evidence.brands??'—'}</strong><span>брендов</span></article><article><strong>{evidence.stock_units??'—'}</strong><span>единиц остатка</span></article><article><strong>{evidence.products_with_sales??'—'}</strong><span>товаров с продажами</span></article></div><small><ShieldCheck size={14}/> Только данные подключённого магазина. Чужие магазины и общая база не используются.</small></section>
  <section className="profilePanel" id="business-profile"><div className="profileIntro"><span>Требуется подтверждение владельца</span><h2>Как устроен ваш бизнес?</h2><p>{data?.profile_decision?.reason||'Выберите основной рабочий сценарий.'}</p></div><div className="modelGrid">{models.map(item=>{const Icon=item.icon;return <button className={selected===item.key?'selected':''} key={item.key} onClick={()=>setSelected(item.key)}><Icon size={22}/><strong>{item.title}</strong><span>{item.text}</span></button>})}</div><button className="confirmProfile" disabled={!selected||saving||!storeId} onClick={confirm}>{saving?'Сохраняем…':data?.profile?'Обновить подтверждённый профиль':'Подтвердить модель бизнеса'}</button></section>
  {data?.costing_questions?.length>0&&<section className="costingPanel"><div><span>Профиль: {data.profile?.label}</span><h2>Что потребуется для точной себестоимости</h2><p>Это список источников, а не рассчитанные значения. Деньги попадут в Profit Center только после подтверждения.</p></div><div>{data.costing_questions.map((item,index)=><article key={item.key}><b>{String(index+1).padStart(2,'0')}</b><div><strong>{item.label}</strong><span>Источник: {item.source}</span></div></article>)}</div><Link href="/profit">Перейти в Profit Center <ChevronRight size={15}/></Link></section>}
  <section className="firstActions"><div><span>Первые действия</span><h2>{data?.status==='ready'?'Ваш стартовый план готов':'Что сделать дальше'}</h2></div>{data?.actions?.map((item,index)=><Link href={item.href} key={item.key}><b>0{index+1}</b><div><strong>{item.title}</strong><span>{item.reason}</span></div><em>{item.action}<ChevronRight size={15}/></em></Link>)}</section>
 </section></main>
}
