import enum
import uuid
from datetime import datetime
from sqlalchemy import Boolean, DateTime, Enum, ForeignKey, Integer, JSON, String, Text, UniqueConstraint, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from .db import Base

class MembershipRole(str,enum.Enum): owner='owner'; admin='admin'; analyst='analyst'; operator='operator'
class SubscriptionStatus(str,enum.Enum): trial='trial'; active='active'; past_due='past_due'; canceled='canceled'
class AccountTokenPurpose(str,enum.Enum): verify_email='verify_email'; reset_password='reset_password'
class JobStatus(str,enum.Enum): queued='queued'; running='running'; succeeded='succeeded'; retry='retry'; dead='dead'; canceled='canceled'
class GenerationStatus(str,enum.Enum): pending='pending'; completed='completed'; failed='failed'
class PublicationStatus(str,enum.Enum): prepared='prepared'; submitting='submitting'; submitted='submitted'; failed='failed'; stale='stale'
class User(Base):
 __tablename__='users'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); email:Mapped[str]=mapped_column(String(320),unique=True,index=True); password_hash:Mapped[str]=mapped_column(String(255)); full_name:Mapped[str]=mapped_column(String(160),default=''); is_active:Mapped[bool]=mapped_column(Boolean,default=True); email_verified:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); memberships:Mapped[list['Membership']]=relationship(back_populates='user',cascade='all, delete-orphan'); legal_consents:Mapped[list['LegalConsent']]=relationship(back_populates='user',cascade='all, delete-orphan'); account_tokens:Mapped[list['AccountActionToken']]=relationship(back_populates='user',cascade='all, delete-orphan'); sessions:Mapped[list['UserSession']]=relationship(back_populates='user',cascade='all, delete-orphan'); security_events:Mapped[list['SecurityEvent']]=relationship(back_populates='user',cascade='all, delete-orphan')
class Workspace(Base):
 __tablename__='workspaces'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); name:Mapped[str]=mapped_column(String(160)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); memberships:Mapped[list['Membership']]=relationship(back_populates='workspace',cascade='all, delete-orphan'); subscriptions:Mapped[list['Subscription']]=relationship(back_populates='workspace',cascade='all, delete-orphan'); stores:Mapped[list['Store']]=relationship(back_populates='workspace',cascade='all, delete-orphan')
class Store(Base):
 __tablename__='stores'; __table_args__=(UniqueConstraint('workspace_id','name',name='uq_store_workspace_name'),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); workspace_id:Mapped[str]=mapped_column(ForeignKey('workspaces.id',ondelete='CASCADE'),index=True); name:Mapped[str]=mapped_column(String(160)); client_name:Mapped[str]=mapped_column(String(160),default=''); is_active:Mapped[bool]=mapped_column(Boolean,default=True,index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); workspace:Mapped[Workspace]=relationship(back_populates='stores'); connections:Mapped[list['MarketplaceConnection']]=relationship(back_populates='store',cascade='all, delete-orphan'); fbo_watches:Mapped[list['FboWatch']]=relationship(back_populates='store',cascade='all, delete-orphan'); snapshots:Mapped[list['MarketplaceSnapshot']]=relationship(back_populates='store',cascade='all, delete-orphan'); beginner_projects:Mapped[list['BeginnerProject']]=relationship(back_populates='store',cascade='all, delete-orphan')
class Membership(Base):
 __tablename__='memberships'; __table_args__=(UniqueConstraint('user_id','workspace_id',name='uq_membership_user_workspace'),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); workspace_id:Mapped[str]=mapped_column(ForeignKey('workspaces.id',ondelete='CASCADE'),index=True); role:Mapped[MembershipRole]=mapped_column(Enum(MembershipRole),default=MembershipRole.owner); user:Mapped[User]=relationship(back_populates='memberships'); workspace:Mapped[Workspace]=relationship(back_populates='memberships')
class Subscription(Base):
 __tablename__='subscriptions'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); workspace_id:Mapped[str]=mapped_column(ForeignKey('workspaces.id',ondelete='CASCADE'),index=True); plan_code:Mapped[str]=mapped_column(String(40),default='trial'); status:Mapped[SubscriptionStatus]=mapped_column(Enum(SubscriptionStatus),default=SubscriptionStatus.trial); provider:Mapped[str|None]=mapped_column(String(40),nullable=True); provider_customer_id:Mapped[str|None]=mapped_column(String(160),nullable=True); provider_subscription_id:Mapped[str|None]=mapped_column(String(160),nullable=True); trial_started_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); trial_expires_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True,index=True); trial_ai_cards_used:Mapped[int]=mapped_column(Integer,default=0); trial_ai_cards_limit:Mapped[int]=mapped_column(Integer,default=5); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); workspace:Mapped[Workspace]=relationship(back_populates='subscriptions')
class LegalConsent(Base):
 __tablename__='legal_consents'; __table_args__=(UniqueConstraint('user_id','document_code','document_version',name='uq_legal_consent_version'),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); document_code:Mapped[str]=mapped_column(String(80),index=True); document_version:Mapped[str]=mapped_column(String(40)); accepted:Mapped[bool]=mapped_column(Boolean,default=True); source:Mapped[str]=mapped_column(String(80),default='web'); accepted_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); user:Mapped[User]=relationship(back_populates='legal_consents')
class AccountActionToken(Base):
 __tablename__='account_action_tokens'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); purpose:Mapped[AccountTokenPurpose]=mapped_column(Enum(AccountTokenPurpose),index=True); token_hash:Mapped[str]=mapped_column(String(64),unique=True,index=True); expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True); used_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); user:Mapped[User]=relationship(back_populates='account_tokens')
class UserSession(Base):
 __tablename__='user_sessions'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); user_agent:Mapped[str]=mapped_column(String(320),default=''); ip_hash:Mapped[str]=mapped_column(String(64),default=''); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); last_seen_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True); revoked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True,index=True); user:Mapped[User]=relationship(back_populates='sessions')
class SecurityEvent(Base):
 __tablename__='security_events'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); user_id:Mapped[str|None]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),nullable=True,index=True); event_type:Mapped[str]=mapped_column(String(80),index=True); success:Mapped[bool]=mapped_column(Boolean,default=True,index=True); subject_hash:Mapped[str]=mapped_column(String(64),default='',index=True); ip_hash:Mapped[str]=mapped_column(String(64),default='',index=True); user_agent:Mapped[str]=mapped_column(String(320),default=''); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),index=True); user:Mapped[User|None]=relationship(back_populates='security_events')
class PushSubscription(Base):
 __tablename__='push_subscriptions'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); endpoint:Mapped[str]=mapped_column(String(2048),unique=True); p256dh:Mapped[str]=mapped_column(String(512)); auth:Mapped[str]=mapped_column(String(512)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class FboWatch(Base):
 __tablename__='fbo_watches'; __table_args__=(UniqueConstraint('store_id','marketplace',name='uq_fbo_watch_store_marketplace'),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); store_id:Mapped[str|None]=mapped_column(ForeignKey('stores.id',ondelete='CASCADE'),nullable=True,index=True); marketplace:Mapped[str]=mapped_column(String(32),default='wildberries'); warehouse_filter:Mapped[str]=mapped_column(String(500),default=''); free_only:Mapped[bool]=mapped_column(Boolean,default=False); enabled:Mapped[bool]=mapped_column(Boolean,default=True,index=True); last_slot_fingerprint:Mapped[str]=mapped_column(String(64),default=''); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); last_checked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); store:Mapped[Store|None]=relationship(back_populates='fbo_watches')
class MarketplaceConnection(Base):
 __tablename__='marketplace_connections'; __table_args__=(UniqueConstraint('store_id','marketplace',name='uq_marketplace_connection_store_marketplace'),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); store_id:Mapped[str|None]=mapped_column(ForeignKey('stores.id',ondelete='CASCADE'),nullable=True,index=True); marketplace:Mapped[str]=mapped_column(String(32),index=True); encrypted_token:Mapped[str]=mapped_column(String(4096)); token_hint:Mapped[str]=mapped_column(String(24),default=''); enabled:Mapped[bool]=mapped_column(Boolean,default=True,index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now()); store:Mapped[Store|None]=relationship(back_populates='connections')
class MarketplaceSnapshot(Base):
 __tablename__='marketplace_snapshots'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); store_id:Mapped[str]=mapped_column(ForeignKey('stores.id',ondelete='CASCADE'),index=True); marketplace:Mapped[str]=mapped_column(String(32),index=True); snapshot_type:Mapped[str]=mapped_column(String(80),index=True); schema_version:Mapped[int]=mapped_column(Integer,default=1); payload:Mapped[dict]=mapped_column(JSON,default=dict); source_updated_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),index=True); store:Mapped[Store]=relationship(back_populates='snapshots')
class BeginnerProject(Base):
 __tablename__='beginner_projects'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); store_id:Mapped[str]=mapped_column(ForeignKey('stores.id',ondelete='CASCADE'),index=True); created_by_user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); title:Mapped[str]=mapped_column(String(160),default='Новый товар'); stage:Mapped[str]=mapped_column(String(40),default='facts',index=True); state:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),index=True); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now(),index=True); store:Mapped[Store]=relationship(back_populates='beginner_projects')
class AIGeneration(Base):
 __tablename__='ai_generations'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); workspace_id:Mapped[str]=mapped_column(ForeignKey('workspaces.id',ondelete='CASCADE'),index=True); store_id:Mapped[str]=mapped_column(ForeignKey('stores.id',ondelete='CASCADE'),index=True); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); feature:Mapped[str]=mapped_column(String(80),index=True); subject_type:Mapped[str]=mapped_column(String(40),default='product',index=True); subject_id:Mapped[str]=mapped_column(String(160),index=True); input_hash:Mapped[str]=mapped_column(String(64),index=True); fact_set_sha256:Mapped[str]=mapped_column(String(64),default='',index=True); model:Mapped[str]=mapped_column(String(120),default=''); status:Mapped[GenerationStatus]=mapped_column(Enum(GenerationStatus),default=GenerationStatus.pending,index=True); input_payload:Mapped[dict]=mapped_column(JSON,default=dict); result_payload:Mapped[dict]=mapped_column(JSON,default=dict); token_usage:Mapped[dict]=mapped_column(JSON,default=dict); estimated_cost_microusd:Mapped[int]=mapped_column(Integer,default=0); provider_response_id:Mapped[str]=mapped_column(String(160),default=''); error:Mapped[str]=mapped_column(Text,default=''); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),index=True); completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True,index=True)
class CardPublication(Base):
 __tablename__='card_publications'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); workspace_id:Mapped[str]=mapped_column(ForeignKey('workspaces.id',ondelete='CASCADE'),index=True); store_id:Mapped[str]=mapped_column(ForeignKey('stores.id',ondelete='CASCADE'),index=True); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); generation_id:Mapped[str]=mapped_column(ForeignKey('ai_generations.id',ondelete='RESTRICT'),index=True); marketplace:Mapped[str]=mapped_column(String(32),default='wildberries',index=True); subject_id:Mapped[str]=mapped_column(String(160),index=True); status:Mapped[PublicationStatus]=mapped_column(Enum(PublicationStatus),default=PublicationStatus.prepared,index=True); fact_set_sha256:Mapped[str]=mapped_column(String(64),index=True); source_card_sha256:Mapped[str]=mapped_column(String(64),index=True); payload_sha256:Mapped[str]=mapped_column(String(64),index=True); source_payload:Mapped[dict]=mapped_column(JSON,default=dict); proposed_payload:Mapped[dict]=mapped_column(JSON,default=dict); diff_payload:Mapped[dict]=mapped_column(JSON,default=dict); provider_response:Mapped[dict]=mapped_column(JSON,default=dict); error:Mapped[str]=mapped_column(Text,default=''); attempt_count:Mapped[int]=mapped_column(Integer,default=0); approved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True,index=True); submitted_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True,index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),index=True); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now(),index=True)
class BackgroundJob(Base):
 __tablename__='background_jobs'; __table_args__=(UniqueConstraint('idempotency_key',name='uq_background_job_idempotency'),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); workspace_id:Mapped[str|None]=mapped_column(ForeignKey('workspaces.id',ondelete='CASCADE'),nullable=True,index=True); store_id:Mapped[str|None]=mapped_column(ForeignKey('stores.id',ondelete='CASCADE'),nullable=True,index=True); job_type:Mapped[str]=mapped_column(String(80),index=True); idempotency_key:Mapped[str]=mapped_column(String(255)); payload:Mapped[dict]=mapped_column(JSON,default=dict); status:Mapped[JobStatus]=mapped_column(Enum(JobStatus),default=JobStatus.queued,index=True); priority:Mapped[int]=mapped_column(Integer,default=100,index=True); attempts:Mapped[int]=mapped_column(Integer,default=0); max_attempts:Mapped[int]=mapped_column(Integer,default=5); available_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),index=True); locked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True,index=True); locked_by:Mapped[str]=mapped_column(String(120),default='',index=True); last_error:Mapped[str]=mapped_column(Text,default=''); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),index=True); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now()); finished_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
