import enum
import uuid
from datetime import datetime
from sqlalchemy import Boolean, DateTime, Enum, ForeignKey, String, UniqueConstraint, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from .db import Base

class MembershipRole(str,enum.Enum): owner='owner'; admin='admin'; analyst='analyst'; operator='operator'
class SubscriptionStatus(str,enum.Enum): trial='trial'; active='active'; past_due='past_due'; canceled='canceled'
class AccountTokenPurpose(str,enum.Enum): verify_email='verify_email'; reset_password='reset_password'
class User(Base):
 __tablename__='users'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); email:Mapped[str]=mapped_column(String(320),unique=True,index=True); password_hash:Mapped[str]=mapped_column(String(255)); full_name:Mapped[str]=mapped_column(String(160),default=''); is_active:Mapped[bool]=mapped_column(Boolean,default=True); email_verified:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); memberships:Mapped[list['Membership']]=relationship(back_populates='user',cascade='all, delete-orphan'); legal_consents:Mapped[list['LegalConsent']]=relationship(back_populates='user',cascade='all, delete-orphan'); account_tokens:Mapped[list['AccountActionToken']]=relationship(back_populates='user',cascade='all, delete-orphan'); sessions:Mapped[list['UserSession']]=relationship(back_populates='user',cascade='all, delete-orphan'); security_events:Mapped[list['SecurityEvent']]=relationship(back_populates='user',cascade='all, delete-orphan')
class Workspace(Base):
 __tablename__='workspaces'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); name:Mapped[str]=mapped_column(String(160)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); memberships:Mapped[list['Membership']]=relationship(back_populates='workspace',cascade='all, delete-orphan'); subscriptions:Mapped[list['Subscription']]=relationship(back_populates='workspace',cascade='all, delete-orphan')
class Membership(Base):
 __tablename__='memberships'; __table_args__=(UniqueConstraint('user_id','workspace_id',name='uq_membership_user_workspace'),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); workspace_id:Mapped[str]=mapped_column(ForeignKey('workspaces.id',ondelete='CASCADE'),index=True); role:Mapped[MembershipRole]=mapped_column(Enum(MembershipRole),default=MembershipRole.owner); user:Mapped[User]=relationship(back_populates='memberships'); workspace:Mapped[Workspace]=relationship(back_populates='memberships')
class Subscription(Base):
 __tablename__='subscriptions'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); workspace_id:Mapped[str]=mapped_column(ForeignKey('workspaces.id',ondelete='CASCADE'),index=True); plan_code:Mapped[str]=mapped_column(String(40),default='trial'); status:Mapped[SubscriptionStatus]=mapped_column(Enum(SubscriptionStatus),default=SubscriptionStatus.trial); provider:Mapped[str|None]=mapped_column(String(40),nullable=True); provider_customer_id:Mapped[str|None]=mapped_column(String(160),nullable=True); provider_subscription_id:Mapped[str|None]=mapped_column(String(160),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); workspace:Mapped[Workspace]=relationship(back_populates='subscriptions')
class LegalConsent(Base):
 __tablename__='legal_consents'; __table_args__=(UniqueConstraint('user_id','document_code','document_version',name='uq_legal_consent_version'),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); document_code:Mapped[str]=mapped_column(String(80),index=True); document_version:Mapped[str]=mapped_column(String(40)); accepted:Mapped[bool]=mapped_column(Boolean,default=True); source:Mapped[str]=mapped_column(String(80),default='web'); accepted_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); user:Mapped[User]=relationship(back_populates='legal_consents')
class AccountActionToken(Base):
 __tablename__='account_action_tokens'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); purpose:Mapped[AccountTokenPurpose]=mapped_column(Enum(AccountTokenPurpose),index=True); token_hash:Mapped[str]=mapped_column(String(64),unique=True,index=True); expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True); used_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); user:Mapped[User]=relationship(back_populates='account_tokens')
class UserSession(Base):
 __tablename__='user_sessions'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); user_agent:Mapped[str]=mapped_column(String(320),default=''); ip_hash:Mapped[str]=mapped_column(String(64),default=''); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); last_seen_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True); revoked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True,index=True); user:Mapped[User]=relationship(back_populates='sessions')
class SecurityEvent(Base):
 __tablename__='security_events'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); user_id:Mapped[str|None]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),nullable=True,index=True); event_type:Mapped[str]=mapped_column(String(80),index=True); success:Mapped[bool]=mapped_column(Boolean,default=True,index=True); subject_hash:Mapped[str]=mapped_column(String(64),default='',index=True); ip_hash:Mapped[str]=mapped_column(String(64),default='',index=True); user_agent:Mapped[str]=mapped_column(String(320),default=''); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),index=True); user:Mapped[User|None]=relationship(back_populates='security_events')
class PushSubscription(Base):
 __tablename__='push_subscriptions'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); endpoint:Mapped[str]=mapped_column(String(2048),unique=True); p256dh:Mapped[str]=mapped_column(String(512)); auth:Mapped[str]=mapped_column(String(512)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class FboWatch(Base):
 __tablename__='fbo_watches'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); marketplace:Mapped[str]=mapped_column(String(32),default='wildberries'); warehouse_filter:Mapped[str]=mapped_column(String(500),default=''); free_only:Mapped[bool]=mapped_column(Boolean,default=False); enabled:Mapped[bool]=mapped_column(Boolean,default=True,index=True); last_slot_fingerprint:Mapped[str]=mapped_column(String(64),default=''); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); last_checked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
class MarketplaceConnection(Base):
 __tablename__='marketplace_connections'; __table_args__=(UniqueConstraint('user_id','marketplace',name='uq_marketplace_connection_user_marketplace'),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid.uuid4())); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); marketplace:Mapped[str]=mapped_column(String(32),index=True); encrypted_token:Mapped[str]=mapped_column(String(4096)); token_hint:Mapped[str]=mapped_column(String(24),default=''); enabled:Mapped[bool]=mapped_column(Boolean,default=True,index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
