'use client'

import Link from 'next/link'
import { useEffect,useMemo,useState } from 'react'
import { BarChart3,Bell,Bot,Boxes,BrainCircuit,CircleDollarSign,FileText,Gauge,Megaphone,PackageSearch,Rocket,Search,Settings,ShieldCheck,Sparkles,Star,TrendingDown,TrendingUp,WandSparkles } from 'lucide-react'
import { useActiveStore } from '../lib/useActiveStore'
import { makeDailyGreeting } from '../lib/dailyGreeting'
import BrandLogo from '../components/BrandLogo'

const demoActions=[{severity:'critical',icon:TrendingDown,title:'Profit Center работает на источниках WB',text:'Финансы, реклама, себестоимость и налог сводятся без AI-догадок и двойного списания рекламы.',effect:'live data',href:'/profit',action:'Открыть прибыль'},{severity:'warning',icon:Search,title:'Демо: карточкам нужен SEO-аудит',text:'SEO-приоритеты будут строиться по реальному каталогу и поисковым данным.',effect:'демо',href:'/seo',action:'Открыть SEO'},{severity:'growth',icon:TrendingUp,title:'Smart FBO уже использует реальные снапшоты',text:'Остатки и скорость заказов WB уже сохраняются фоново и доступны для расчётов.',effect:'live data',href:'/products',action:'Открыть товары'}]
const nav=[['Старт с нуля',Rocket,'/start'],['Обзор',Gauge,'/'],['AI Director',BrainCircuit,'/director'],['Profit Center',CircleDollarSign,'/profit'],['Товары',Boxes,'/products'],['AI Card Factory',WandSparkles,'/card-factory'],['SEO',Search,'/seo'],['Реклама',Megaphone,'/ads'],['Отзывы',Star,'/reviews'],['Остатки',PackageSearch,'/inventory'],['Отчёты',FileText,'/reports'],['Автопилот',Bot,'/autopilot']]

export default function HomePage(){
 const [notice,setNotice]=useState(''); const [question,setQuestion]=useState(''); const [answer,setAnswer]=useState(''); const [fullName,setFullName]=useState(''); const [overview,setOverview]=useState(null); const [overviewError,setOverviewError]=useState('')
 const {storeId,storeName}=useActiveStore()
 useEffect(()=>{let active=true;fetch('/api/auth/me',{cache:'no-store'}).then(async r=>r.ok?r.json():null).then(p=>{if(active&&p)setFullName(p.full_name||p.name||'')}).catch(()=>{});return()=>{active=false}},[])
 useEffect(()=>{if(!storeId){setOverview(null);return}let active=true;setOverviewError('');fetch(`/api/seller-data/overview?store_id=${encodeURIComponent(storeId)}`,{cache:'no-store'}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error||'Не удалось загрузить показатели');if(active)setOverview(p)}).catch(e=>active&&setOverviewError(e.message));return()=>{active=false}},[storeId])
 const greeting=useMemo(()=>makeDailyGreeting(fullName),[fullName])
 const k=overview?.kpis
 const metrics=k?[{label:'Заказы за 7 дней',value:String(k.orders_7d),delta:`≈ ${k.avg_orders_per_day}/день`,tone:'good'},{label:'Остаток WB',value:`${k.stock_units} шт.`,delta:`${k.low_stock_products} SKU с низким запасом`,tone:k.low_stock_products?'neutral':'good'},{label:'Товаров с историей',value:String(k.products_with_history),delta:`Активных: ${k.active_products}`,tone:'neutral'},{label:'Свежесть данных',value:overview.freshness?.age_seconds!=null?`${Math.floor(overview.freshness.age_seconds/60)} мин`:'—',delta:overview.sync_required?'Обновление в очереди':'Снапшот актуален',tone:overview.sync_required?'neutral':'good'}]:[{label:'Заказы за 7 дней',value:'—',delta:'Ожидаем синхронизацию WB',tone:'neutral'},{label:'Остаток WB',value:'—',delta:'Ожидаем данные',tone:'neutral'},{label:'Товаров с историей',value:'—',delta:'Ожидаем данные',tone:'neutral'},{label:'Свежесть данных',value:'—',delta:'Нет снапшота',tone:'neutral'}]
 function ask(){if(!question.trim())return;setAnswer(`AI принял вопрос: «${question.trim()}». Ответы по цифрам будут строиться только из данных активного магазина${storeName?` «${storeName}»`:''}.`)}
 return <main className="shell"><aside className="sidebar"><BrandLogo />
 <nav className="nav">{nav.map(([label,Icon,href])=><Link key={label} href={href} className={label==='Обзор'?'navItem active':'navItem'}><Icon size={18}/><span>{label}</span>{label==='Старт с нуля'&&<b>new</b>}{label==='AI Director'&&<b>demo</b>}</Link>)}</nav>
 <div className="marketplaces"><span className="eyebrow">МАРКЕТПЛЕЙСЫ</span><button className="marketRow" onClick={()=>setNotice(`Wildberries привязан к активному магазину: ${storeName||'магазин не выбран'}.`)}><i className="wbDot"/>Wildberries <span>○</span></button><button className="marketRow" onClick={()=>setNotice('Ozon будет подключён после завершения проверенной WB-версии продукта.')}><i className="ozonDot"/>Ozon <span>○</span></button></div><Link href="/account" className="settingsBtn"><Settings size={18}/> Настройки</Link></aside>
 <section className="workspace"><header className="topbar"><div><span className="eyebrow">ПАНЕЛЬ УПРАВЛЕНИЯ · {storeName||'МАГАЗИН НЕ ВЫБРАН'}</span><h1>{greeting.phrase}</h1><small>{greeting.tip}</small></div><div className="topActions"><button className="iconBtn" onClick={()=>setNotice('Новых системных уведомлений пока нет.')}><Bell size={19}/><span className="notificationDot"/></button><Link href="/account" className="profile"><div className="avatar">AI</div><div><strong>{storeName||'Мой магазин'}</strong><span>Аккаунт и подключения</span></div></Link></div></header>
 {notice&&<div className="panel" style={{marginBottom:16,padding:14}}>{notice}</div>}{overviewError&&<div className="panel" style={{marginBottom:16,padding:14}}>{overviewError}</div>}
 <section className="hero"><div><div className="heroKicker"><BrainCircuit size={17}/> AI Director</div><h2>Реальные <em>KPI, финансы и реклама WB</em> уже читаются из источников магазина.</h2><p>SEO и будущие рекомендации AI Director остаются демо, пока для них не подключены и не проверены отдельные источники.</p></div><Link className="primaryBtn" href="/profit"><Sparkles size={18}/> Открыть Profit Center</Link></section>
 <section className="metricsGrid">{metrics.map(m=><article className="metricCard" key={m.label}><span>{m.label}</span><strong>{m.value}</strong><small className={m.tone}>{m.delta}</small></article>)}</section>
 <section className="contentGrid"><div className="panel opportunities"><div className="panelTitle"><div><span className="eyebrow">ПРИОРИТЕТЫ</span><h3>Что требует внимания</h3></div><Link className="ghostBtn" href="/director">AI Director</Link></div><div className="actionList">{demoActions.map(({severity,icon:Icon,title,text,effect,href,action})=><article className={`actionCard ${severity}`} key={title}><div className="actionIcon"><Icon size={20}/></div><div className="actionBody"><div className="actionHeader"><h4>{title}</h4><span>{effect}</span></div><p>{text}</p><Link className="ghostBtn" href={href}>{action}</Link></div></article>)}</div></div>
 <aside className="rightColumn"><Link className="panel profitCard" href="/profit"><div className="panelTitle compact"><div><span className="eyebrow">PROFIT CENTER · LIVE SOURCES</span><h3>Прибыль без выдуманных данных</h3></div><BarChart3 size={20}/></div><div className="profitValue">WB</div><div className="profitDelta">Финансы · реклама · COGS · налог</div></Link><Link className="panel autopilotCard" href="/autopilot"><div className="autopilotHeader"><div className="shield"><ShieldCheck size={20}/></div><div><span className="eyebrow">AUTOPILOT</span><h3>Безопасный режим</h3></div></div><p>AI наблюдает за выбранным магазином и будет выполнять только разрешённые действия.</p></Link></aside></section>
 <section className="askAI"><div className="askIcon"><Bot size={23}/></div><div className="askCopy"><strong>Спросить AI о бизнесе</strong><span>Например: какие SKU рискуют закончиться?</span></div><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="Введите вопрос…"/><button onClick={ask}><Sparkles size={18}/> Спросить AI</button></section>{answer&&<div className="panel" style={{marginTop:12,padding:16}}>{answer}</div>}
 </section></main>
}
