'use client'

import Link from 'next/link'
import { useState } from 'react'
import { BarChart3,Bell,Bot,Boxes,BrainCircuit,CircleDollarSign,FileText,Gauge,Megaphone,PackageSearch,Search,Settings,ShieldCheck,Sparkles,Star,TrendingDown,TrendingUp,WandSparkles } from 'lucide-react'
import { useActiveStore } from '../lib/useActiveStore'

const metrics=[{label:'Выручка сегодня',value:'482 640 ₽',delta:'+14,8%',tone:'good'},{label:'Чистая прибыль',value:'127 430 ₽',delta:'+21,3%',tone:'good'},{label:'Реклама',value:'41 280 ₽',delta:'ДРР 8,6%',tone:'neutral'},{label:'Заказы',value:'327',delta:'+38',tone:'good'}]
const actions=[{severity:'critical',icon:TrendingDown,title:'SKU 18374629 уходит в убыток',text:'Реклама выросла на 37%, а маржа стала отрицательной. Потеря за 24 часа: 4 320 ₽.',effect:'+9 800 ₽/нед',href:'/ads',action:'Исправить рекламу'},{severity:'warning',icon:Search,title:'У 6 карточек просело SEO',text:'AI нашёл новые поисковые кластеры и подготовил обновлённые заголовки и описание.',effect:'+11–18% трафика',href:'/seo',action:'Обновить SEO'},{severity:'growth',icon:TrendingUp,title:'3 товара готовы к масштабированию',text:'Высокая маржа, стабильная конверсия и запас на 21 день. Можно безопасно увеличить трафик.',effect:'+74 000 ₽/мес',href:'/products',action:'Запустить рост'}]
const nav=[['Обзор',Gauge,'/'],['AI Director',BrainCircuit,'/director'],['Profit Center',CircleDollarSign,'/profit'],['Товары',Boxes,'/products'],['AI Card Factory',WandSparkles,'/card-factory'],['SEO',Search,'/seo'],['Реклама',Megaphone,'/ads'],['Отзывы',Star,'/reviews'],['Остатки',PackageSearch,'/inventory'],['Отчёты',FileText,'/reports'],['Автопилот',Bot,'/autopilot']]

export default function HomePage(){
 const [notice,setNotice]=useState(''); const [question,setQuestion]=useState(''); const [answer,setAnswer]=useState('')
 const {storeName}=useActiveStore()
 function ask(){if(!question.trim())return;setAnswer(`AI принял вопрос: «${question.trim()}». После подключения реальных данных ответ будет строиться только по активному магазину${storeName?` «${storeName}»`:''}.`)}
 return <main className="shell"><aside className="sidebar"><div className="brand"><div className="brandMark"><Sparkles size={20}/></div><div><strong>Marketplace AI</strong><span>Studio Cloud</span></div></div>
 <nav className="nav">{nav.map(([label,Icon,href],i)=><Link key={label} href={href} className={i===0?'navItem active':'navItem'}><Icon size={18}/><span>{label}</span>{label==='AI Director'&&<b>17</b>}</Link>)}</nav>
 <div className="marketplaces"><span className="eyebrow">МАРКЕТПЛЕЙСЫ</span><button className="marketRow" onClick={()=>setNotice(`Wildberries подключается отдельно для каждого магазина. Активный контекст: ${storeName||'магазин не выбран'}.`)}><i className="wbDot"/>Wildberries <span>○</span></button><button className="marketRow" onClick={()=>setNotice('Ozon будет подключаться по той же магазинной схеме после завершения проверенной API-интеграции.')}><i className="ozonDot"/>Ozon <span>○</span></button></div><Link href="/account" className="settingsBtn"><Settings size={18}/> Настройки</Link></aside>
 <section className="workspace"><header className="topbar"><div><span className="eyebrow">ПАНЕЛЬ УПРАВЛЕНИЯ · {storeName||'МАГАЗИН НЕ ВЫБРАН'}</span><h1>Доброе утро 👋</h1><small>Сводка ключевых показателей и приоритетов активного магазина.</small></div><div className="topActions"><button className="iconBtn" onClick={()=>setNotice('Новых системных уведомлений пока нет.')}><Bell size={19}/><span className="notificationDot"/></button><Link href="/account" className="profile"><div className="avatar">SB</div><div><strong>{storeName||'Мой магазин'}</strong><span>Аккаунт и подключения</span></div></Link></div></header>
 {notice&&<div className="panel" style={{marginBottom:16,padding:14}}>{notice}</div>}
 <section className="hero"><div><div className="heroKicker"><BrainCircuit size={17}/> AI Director</div><h2>Демо-режим показывает, как AI будет находить <em>возможности роста</em> по активному магазину.</h2><p>Реальные действия не отправляются в маркетплейс без подключения, разрешения и выбранного Store Context.</p></div><Link className="primaryBtn" href="/director"><Sparkles size={18}/> Открыть план действий</Link></section>
 <section className="metricsGrid">{metrics.map(m=><article className="metricCard" key={m.label}><span>{m.label}</span><strong>{m.value}</strong><small className={m.tone}>{m.delta}</small></article>)}</section>
 <section className="contentGrid"><div className="panel opportunities"><div className="panelTitle"><div><span className="eyebrow">ПРИОРИТЕТЫ AI</span><h3>Что требует внимания</h3></div><Link className="ghostBtn" href="/director">Все 17</Link></div><div className="actionList">{actions.map(({severity,icon:Icon,title,text,effect,href,action})=><article className={`actionCard ${severity}`} key={title}><div className="actionIcon"><Icon size={20}/></div><div className="actionBody"><div className="actionHeader"><h4>{title}</h4><span>{effect}</span></div><p>{text}</p><Link className="ghostBtn" href={href}>{action}</Link></div></article>)}</div></div>
 <aside className="rightColumn"><Link className="panel profitCard" href="/profit"><div className="panelTitle compact"><div><span className="eyebrow">PROFIT CENTER</span><h3>Прибыль за 30 дней</h3></div><BarChart3 size={20}/></div><div className="profitValue">1 846 320 ₽</div><div className="profitDelta"><TrendingUp size={16}/> +18,4% к прошлому периоду</div><div className="bars">{[52,62,48,73,66,84,78,92,74,88,96,100].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><div className="profitFooter"><span>Маржа <strong>26,4%</strong></span><span>ДРР <strong>9,1%</strong></span></div></Link><Link className="panel autopilotCard" href="/autopilot"><div className="autopilotHeader"><div className="shield"><ShieldCheck size={20}/></div><div><span className="eyebrow">AUTOPILOT</span><h3>Безопасный режим</h3></div></div><p>AI наблюдает за выбранным магазином, создаёт рекомендации и выполняет только разрешённые действия.</p></Link></aside></section>
 <section className="askAI"><div className="askIcon"><Bot size={23}/></div><div className="askCopy"><strong>Спросить AI о бизнесе</strong><span>Например: почему вчера упали продажи?</span></div><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="Введите вопрос…"/><button onClick={ask}><Sparkles size={18}/> Спросить AI</button></section>{answer&&<div className="panel" style={{marginTop:12,padding:16}}>{answer}</div>}
 </section></main>
}
